
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: demo-template
  title: Just a demo template v0.0.5
  description: Creates a simple repo with a README.md file
  tags:
    - demo
spec:
  owner: crivetechie
  type: service

  parameters:
    - title: Fill in the details
      required:
        - name
        - description
      properties:
      ***

    - title: Choose a location
      required:
        - repoUrl
      properties:
      ***
      
  steps:
  ***       

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
